import datetime

print(dir(datetime))
x = datetime.datetime.now()
y = datetime.datetime(2025, 10, 3)
print(x)
print(y)
# print()
print(datetime.MAXYEAR)
print(datetime.MINYEAR)

print(x.year, x.strftime("%A"))

print(x.strftime("%a"))

print(x.strftime("%x").replace("/", '-'))

print(x.strftime("%I:%M:%S %p"))

print(x.strftime("%H:%M:%S"))

print(x.strftime("%B"))
print(x.strftime("%b"))
print(x.strftime("%d"))
print(x.strftime("%m"))
print(x.strftime("%Y"))
print(x.strftime("%y"))
print(x.strftime("%f"))
print(x.strftime("%j"))
print(x.strftime("%U"))
print(x.strftime("%W"))
print(x.strftime("%c"))
print(x.strftime("%C"))
print(x.strftime("%G"))
print(x.strftime("%g"))
print(x.strftime("%V"))
print(x.strftime("%z"))
print(x.strftime("%Z"))
print(x.strftime("%%"))
print(x.strftime("%w"))
print(x.strftime("%D"))
print(x.strftime("%e"))
print(x.strftime("%s"))  # Unix timestamp
print(x.strftime("%X"))
print(x.strftime("%T"))
print(x.strftime("%u"))
print(x.strftime("%p"))
print(x.strftime("%r"))
print(x.strftime("%R"))
print(x.strftime("%S"))
print(x.strftime("%M"))
print(x.strftime("%H"))
print(x.strftime("%I"))
print(x.strftime("%m"))
print(x.strftime("%d"))
